//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CarrerasSedes
    {
        public int Id_CarreraLF { get; set; }
        public int Id_SedeLF { get; set; }
        public System.DateTime FechaImparte { get; set; }
    
        public virtual Carrera Carrera { get; set; }
        public virtual Sede Sede { get; set; }
    }
}
