//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Curso_Estudiante
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Curso_Estudiante()
        {
            this.MatriculaCurso = new HashSet<MatriculaCurso>();
        }
    
        public int Id_CursoEstudiante { get; set; }
        public int Id_CursoLectivo { get; set; }
        public int Id_Estudiante { get; set; }
        public string Estado { get; set; }
        public int Nota { get; set; }
    
        public virtual CursoLectivo CursoLectivo { get; set; }
        public virtual Estudiante Estudiante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MatriculaCurso> MatriculaCurso { get; set; }
    }
}
