//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CursoLectivo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CursoLectivo()
        {
            this.Curso_Estudiante = new HashSet<Curso_Estudiante>();
            this.Horario = new HashSet<Horario>();
        }
    
        public int Id_CursoLectivo { get; set; }
        public string CursoLectivo1 { get; set; }
        public int Maximo { get; set; }
        public int Sobrante { get; set; }
        public int Id_Profesor { get; set; }
        public int Id_Curso { get; set; }
        public int Id_Periodo { get; set; }
    
        public virtual Curso Curso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Curso_Estudiante> Curso_Estudiante { get; set; }
        public virtual Periodo Periodo { get; set; }
        public virtual Profesor Profesor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Horario> Horario { get; set; }
    }
}
