//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Horario
    {
        public int Id_CursoLectivoLF { get; set; }
        public int Id_DiaSemanaLF { get; set; }
        public System.TimeSpan HoraInicio { get; set; }
        public System.TimeSpan HoraFin { get; set; }
    
        public virtual CursoLectivo CursoLectivo { get; set; }
        public virtual DiaSemana DiaSemana { get; set; }
    }
}
