//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public int Id_PlanEstudioLF { get; set; }
        public int Id_CursoLF { get; set; }
        public int Id_CursoRequisito { get; set; }
        public bool Corequisito { get; set; }
    
        public virtual Bloque Bloque { get; set; }
    }
}
