//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UniversidadWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Temario
    {
        public int Id_Temario { get; set; }
        public int Id_Curso { get; set; }
        public string Temario1 { get; set; }
    
        public virtual Curso Curso { get; set; }
    }
}
